/**
 * @file fileio.c
 * @brief Implementation of file input/output operations for trigonometric approximation analysis (direct method).
 *
 * Contains functions for saving data points, sample nodes, appending heatmap errors (N, m, Errors),
 * and generating a Gnuplot script to visualize individual approximation results,
 * parameterized by max harmonic 'm' and respecting the m < n/2 condition.
 */
#include "../include/fileio.h" // Function prototypes and common includes (common.h)
#include <stdio.h>             // Standard I/O functions (fopen, fprintf, fclose, FILE)
#include <stdlib.h>            // Standard library
#include <string.h>            // For string manipulation (like snprintf)
#include <math.h>              // For NAN, isnan

// saveDataToFile: Saves generic (x, y) data. Remains unchanged.
void saveDataToFile(const char* filename, double x[], double y[], int n) {
    char filepath[256];
    snprintf(filepath, sizeof(filepath), "data/%s", filename);

    FILE *file = fopen(filepath, "w");
    if (file == NULL) {
        fprintf(stderr, "Error [saveDataToFile]: Could not open file: %s\n", filepath);
        return;
    }

    for (int i = 0; i < n; i++) {
        fprintf(file, "%lf %lf\n", x[i], y[i]);
    }

    fclose(file);
}

// saveNodesToFile: Saves sample points (x, y). Remains unchanged.
void saveNodesToFile(const char* filename, double points_x[], double points_y[], int n) {
    char filepath[256];
    snprintf(filepath, sizeof(filepath), "data/%s", filename);

    FILE *file = fopen(filepath, "w");
    if (file == NULL) {
        fprintf(stderr, "Error [saveNodesToFile]: Could not open file: %s\n", filepath);
        return;
    }

    for (int i = 0; i < n; i++) {
        fprintf(file, "%lf %lf\n", points_x[i], points_y[i]);
    }

    fclose(file);
}


/**
 * @brief Appends approximation errors (N, m, Max Absolute, MSE) to a CSV file for heatmap plotting.
 *
 * Writes a single row for a specific (n, m) combination. Handles NAN values.
 * Parameter 'm' is the max harmonic order.
 */
void appendErrorToHeatmapFile(FILE* file, int n, int m, double max_error, double mse_error) {
    if (file == NULL) {
        fprintf(stderr, "Error [appendErrorToHeatmapFile]: Invalid file pointer.\n");
        return;
    }
    // Write n, m (max harmonic), max_error, and mse_error.
    // Use %.10e for scientific notation. Write "NAN" string if value is NaN.
    fprintf(file, "%d,%d,", n, m); // Use 'm' here
    if (isnan(max_error)) {
        fprintf(file, "NAN,");
    } else {
        fprintf(file, "%.10e,", max_error);
    }
    if (isnan(mse_error)) {
        fprintf(file, "NAN\n");
    } else {
        fprintf(file, "%.10e\n", mse_error);
    }
}


/**
 * @brief Generates a single Gnuplot script ('scripts/plot_all_trig_approximations.gp')
 *        to visualize individual trigonometric approximation results for valid (n, m) combinations (m < n/2).
 *
 * Creates the script using nested loops and includes a check for the existence of the
 * approximation data file before attempting to plot it, ensuring robustness even if
 * some calculations failed or were skipped due to the m < n/2 condition.
 */
void generateAllIndividualTrigApproxScripts(int min_n, int max_n, int max_m) {
    char script_path[256];
    // Use a consistent script name
    snprintf(script_path, sizeof(script_path), "scripts/plot_all_trig_approximations.gp");

    FILE *gnuplot_script = fopen(script_path, "w");
    if (gnuplot_script == NULL) {
        fprintf(stderr,"Error [generateAllIndividualTrigApproxScripts]: Cannot open file %s for writing.\n", script_path);
        return;
    }

    // --- Common Gnuplot Settings ---
    fprintf(gnuplot_script, "# Gnuplot script: Plot individual trigonometric approximation results (Direct Method, m < n/2)\n");
    fprintf(gnuplot_script, "# Generated by: C program (main.c -> generateAllIndividualTrigApproxScripts)\n\n");
    fprintf(gnuplot_script, "# Ensure required directories exist\n");
    fprintf(gnuplot_script, "system 'mkdir -p plots data'\n\n");
    fprintf(gnuplot_script, "# Terminal settings (PNG output)\n");
    fprintf(gnuplot_script, "set terminal pngcairo enhanced size 1200,800 font 'Arial,12'\n");
    fprintf(gnuplot_script, "set grid\n");
    fprintf(gnuplot_script, "set key top right outside spacing 1.1\n");
    fprintf(gnuplot_script, "set xlabel 'x'\n");
    fprintf(gnuplot_script, "set ylabel 'f(x), T_m(x)'\n");
    fprintf(gnuplot_script, "set xrange [%.4f:%.4f]\n", a, b); // Use global interval bounds
    // Adjust yrange if necessary based on function behavior
    fprintf(gnuplot_script, "set yrange [-15:15]\n");
    fprintf(gnuplot_script, "\n# Define maximum harmonic 'm' used in loops\n");
    fprintf(gnuplot_script, "max_m = %d\n\n", max_m);

    // --- Gnuplot Nested Loops ---
    fprintf(gnuplot_script, "# Loop through number of points n\n");
    fprintf(gnuplot_script, "do for [n=%d:%d] {\n", min_n, max_n);
    fprintf(gnuplot_script, "    print sprintf(\"Gnuplot: Processing n = %%d\", n)\n"); // Progress indicator
    fprintf(gnuplot_script, "    # Loop through max harmonic m\n");
    fprintf(gnuplot_script, "    do for [m=0:max_m] {\n");
    // --- Condition Check (m < n/2) inside Gnuplot ---
    // Use 2.0 for floating point division, crucial for odd n
    fprintf(gnuplot_script, "        if (m < n / 2.0) {\n");
    fprintf(gnuplot_script, "            # Define filenames for this (n, m) combination\n");
    fprintf(gnuplot_script, "            sample_file = sprintf(\"data/sample_points_n%%d.dat\", n)\n");
    fprintf(gnuplot_script, "            approx_file = sprintf(\"data/trig_approx_m%%d_points%%d.dat\", m, n)\n");
    fprintf(gnuplot_script, "            output_png = sprintf('plots/trig_approx_m%%d_n%%d.png', m, n)\n");
    fprintf(gnuplot_script, "            plot_title = sprintf(\"Trigonometric Approx (n=%%d points, max harmonic m=%%d)\", n, m)\n\n");
    fprintf(gnuplot_script, "            set output output_png\n");
    fprintf(gnuplot_script, "            set title plot_title\n\n");
    fprintf(gnuplot_script, "            plot 'data/original_function_plot.dat' \\\n");
    fprintf(gnuplot_script, "                    with lines dashtype 2 lw 3 lc rgb 'blue' title 'Original function f(x)', \\\n");
    fprintf(gnuplot_script, "                 approx_file using 1:2 \\\n");
    fprintf(gnuplot_script, "                    with lines lw 3 lc rgb 'red' title sprintf('Approximating T_{%%d}(x)', m), \\\n");
    fprintf(gnuplot_script, "                 sample_file \\\n");
    fprintf(gnuplot_script, "                    with points pt 7 ps 1.5 lc rgb 'black' title 'Sample points (x_i, y_i)'\n");
    fprintf(gnuplot_script, "        } \n");
    fprintf(gnuplot_script, "    } \n");
    fprintf(gnuplot_script, "} \n\n");
    fprintf(gnuplot_script, "print \"Gnuplot script finished.\"\n");

    fclose(gnuplot_script);
    printf("Generated Gnuplot script for individual trigonometric approximations: %s\n", script_path);
    printf("Note: Gnuplot script uses fileexists() (Gnuplot >= 5.2) to check for approximation data files.\n");
}